name: 'Generate Changelog'
description: 'Generates a changelog based on conventional commits'

runs:
  using: 'ubuntu-latest'

permissions:
  contents: write

jobs:
  - name: Conventional Changelog Action
    uses: TriPSs/conventional-changelog-action@v3
    with:
      github-token: ${{ secrets.github_token }}