name: 'Generate Changelog'
description: 'Generates a changelog based on conventional commits'

inputs: 
  github-token:
    description: ''GitHub token utilized for connecting to the repository'
    required: true

permissions:
    id-token: write
    contents: write

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: conventional changelog action
      # https://github.com/TriPSs/conventional-changelog-action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: github-token